seq_file: sequences.dat
codes_path: /home/tb/samukher/DATA/.bin/COCOCMO/MODULES
resources: CUDA
forcefield: cocomo2
temp: 300.0
press: 1.0
time_step: 0.01
friction: 0.01
eq_mini: 50
eq_nstep: 50
eq_nstout: 50
eq_nstdcd: 50
eq_switching: false
eq_press_couple: false
eq_p_iso: true
eq_p_aniso_x: false
eq_p_aniso_y: false
eq_p_aniso_z: false
eq_genpsf: true
eq_chk_int: 500000
prod_mini: 5000000
prod_nstep: 500000
prod_nstout: 500
prod_nstdcd: 50
prod_switching: false
prod_press_couple: false
prod_p_iso: true
prod_p_aniso_x: false
prod_p_aniso_y: false
prod_p_aniso_z: false
prod_genpsf: false
prod_chk_int: 500000
box_type: cube
geometry: coil
box_dim: [30,30,30]
cube_add: 0
slab_add: 500
chain_dist: 0.5
chain_pos: center
temp_pdb: temp.pdb
initial_pdb: initial.pdb
psf_file: topol.psf
eq_dcd: eqm.dcd
eq_log: eqm.log
eq_pdb: eqm.pdb
prod_dcd: prod.dcd
prod_log: prod.log
prod_pdb: prod.pdb
eq_param: eqm.dat
prod_param: prod.dat
log: simulation.log
